unit TestuspClasses.ClientDataSetUtils;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, VCL.DBGrids, Data.DB, System.SysUtils, DataSnap.DBClient,
  uspClasses.ClientDataSetUtils, Math;

type
  // Test methods for class TClientDataSetAux

  TestTClientDataSetAux = class(TTestCase)
  strict private
    FClientDataSetAux: TClientDataSetAux;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCalculaTotalColuna;
    procedure TestCalculaTotalDivisoesColuna;
  end;

implementation

procedure TestTClientDataSetAux.SetUp;
var
  Grid : TDBGrid;
begin
  Grid := TDBGrid.Create(nil);
  FClientDataSetAux := TClientDataSetAux.Create(Grid);
end;

procedure TestTClientDataSetAux.TearDown;
begin
  FClientDataSetAux.Free;
  FClientDataSetAux := nil;
end;

procedure TestTClientDataSetAux.TestCalculaTotalColuna;
var
  ReturnValue: Double;
  IndiceColuna: Integer;
  I : integer;
  ValorCorreto : Double;
begin
  // TODO: Setup method call parameters
  IndiceColuna := 2;
  for I := 1 to 10 do
  begin
    FClientDataSetAux.ClientDataSet.Append;
    FClientDataSetAux.ClientDataSet.FieldByName('IdProjeto').AsInteger   := I ;
    FClientDataSetAux.ClientDataSet.FieldByName('NomeProjeto').AsString  := 'Projeto ' + IntToStr(I) ;
    FClientDataSetAux.ClientDataSet.FieldByName('Valor').AsFloat         := I*10;
    FClientDataSetAux.ClientDataSet.Post;
  end;
  ValorCorreto := 550;
  ReturnValue := RoundTo( FClientDataSetAux.CalculaTotalColuna(IndiceColuna), -2);
  // TODO: Validate method results
  if ValorCorreto <> ReturnValue then
    raise Exception.Create('Valor errado: ' + FormatFloat('#0,.00', ReturnValue));
end;

procedure TestTClientDataSetAux.TestCalculaTotalDivisoesColuna;
var
  ReturnValue: Double;
  IndiceColuna: Integer;
  ValorCorreto : Double;
  I : Integer;
begin
  // TODO: Setup method call parameters
  IndiceColuna := 2;
  for I := 1 to 10 do
  begin
    FClientDataSetAux.ClientDataSet.Append;
    FClientDataSetAux.ClientDataSet.FieldByName('IdProjeto').AsInteger   := I ;
    FClientDataSetAux.ClientDataSet.FieldByName('NomeProjeto').AsString  := 'Projeto ' + IntToStr(I) ;
    FClientDataSetAux.ClientDataSet.FieldByName('Valor').AsFloat         := I*10;
    FClientDataSetAux.ClientDataSet.Post;
  end;
  ValorCorreto := 11.83;
  ReturnValue := RoundTo( FClientDataSetAux.CalculaTotalDivisoesColuna(IndiceColuna), -2);
  if ValorCorreto <> ReturnValue then
    raise Exception.Create('Valor errado: ' + FormatFloat('#0,.00', ReturnValue));
  // TODO: Validate method results

end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTClientDataSetAux.Suite);
end.

