unit TestuspClasses.Contador;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Classes, VCL.ComCtrls, Controls, uspClasses.Contador, System.SysUtils,
  System.threading, StdCtrls, DUnitX.TestFramework, Vcl.Forms;

type
  // Test methods for class TContador

  TestTContador = class(TTestCase)
  strict private
    FContador: TContador;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestExecute;
  end;

implementation

procedure TestTContador.SetUp;
begin
  FContador := TContador.Create;
end;

procedure TestTContador.TearDown;
begin
//  FContador.Free;
//  FContador := nil;
end;

procedure TestTContador.TestExecute;
var
  Contador : TContador;
begin
  Contador := TContador.Create;
  Contador.Intervalo        := 100;
  Contador.QuantidadeLoops  := 100;
  Contador.barraProgresso   := nil;
  Contador.Resume;

 while not Contador.Finished do sleep( 1000 );
  Assert.isTrue(Contador.Finished, 'Thread finalizou com sucesso');
  Assert.IsTrue((not Contador.Suspended),'Thread não iniciou')
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTContador.Suite);
end.

