unit TestuspQuery;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, FireDAC.Comp.Client, Data.DB, System.SysUtils, uspQuery,
  FireDAC.Comp.DataSet, System.Classes, FireDAC.Phys.ODBCBase, FireDAC.DApt;

type
  // Test methods for class TspQuery

  TestTspQuery = class(TTestCase)
  strict private
    FspQuery: TspQuery;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGeraSQL;
  end;

implementation

procedure TestTspQuery.SetUp;
begin
  FspQuery := TspQuery.Create(nil);
end;

procedure TestTspQuery.TearDown;
begin
  FspQuery.Free;
  FspQuery := nil;
end;

procedure TestTspQuery.TestGeraSQL;
var
  slSQLEsperado : TStrings;
begin
  slSQLEsperado := TStringList.Create;
  slSQLEsperado.Clear;
  slSQLEsperado.Add('SELECT CLI_NOME');
  slSQLEsperado.Add('FROM cliente');
  slSQLEsperado.Add('where CLI_NOME="RODRIGO"');

  FspQuery.spColunas.Add('CLI_NOME');
  FspQuery.spTabelas.Add('cliente');
  FspQuery.spCondicoes.Add('CLI_NOME="RODRIGO"');


  FspQuery.GeraSQL;
  if Trim(FspQuery.SQL.Text) <> Trim(slSQLEsperado.Text) then
    raise Exception.Create('SQL Gerado incorreto: ' + sLineBreak +
      FspQuery.SQL.text + sLineBreak +
      slSQLEsperado.text); ;
  slSQLEsperado.Free;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTspQuery.Suite);
end.

